import jsPDF from 'jspdf';
import type { AuditResult } from '../types';

// ========================
// MARKDOWN EXPORT
// ========================
export function exportToMarkdown(result: AuditResult): string {
    const { summary } = result;
    const now = new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' });
    const riskLevel = summary.securityScore < 30 ? 'CRITICAL' : summary.securityScore < 50 ? 'HIGH' : summary.securityScore < 80 ? 'MODERATE' : 'LOW';

    let md = `# 🛡️ AnchorGuard AI — Security Audit Report\n\n`;
    md += `**Generated:** ${now}  \n`;
    md += `**Engine:** Hybrid AI (Groq + Gemini)  \n`;
    md += `**Risk Level:** ${riskLevel}  \n\n`;
    md += `---\n\n`;

    // Summary
    md += `## 📊 Audit Summary\n\n`;
    md += `| Metric | Value |\n`;
    md += `|--------|-------|\n`;
    md += `| Security Score | **${summary.securityScore}/100** |\n`;
    md += `| Total Issues | ${summary.totalIssues} |\n`;
    md += `| 🔴 Critical | ${summary.critical} |\n`;
    md += `| 🟠 High | ${summary.high} |\n`;
    md += `| 🟡 Medium | ${summary.medium} |\n`;
    md += `| 🟢 Safe Patterns | ${summary.safe} |\n`;
    md += `| ⚡ Compute Optimizations | ${summary.computeOptimizations} |\n\n`;

    // Vulnerabilities
    if (result.vulnerabilities.length > 0) {
        md += `## 🔍 Detected Vulnerabilities\n\n`;
        result.vulnerabilities.forEach((vuln, i) => {
            const icon = vuln.severity === 'critical' ? '🔴' : vuln.severity === 'high' ? '🟠' : vuln.severity === 'medium' ? '🟡' : '🟢';
            md += `### ${i + 1}. ${icon} ${vuln.title}\n\n`;
            md += `- **Severity:** \`${vuln.severity.toUpperCase()}\`\n`;
            md += `- **Category:** ${vuln.category}\n`;
            md += `- **Line:** ~${vuln.line}\n`;
            md += `- **Description:** ${vuln.description}\n\n`;

            md += `**Vulnerable Code:**\n\`\`\`rust\n${vuln.originalCode}\n\`\`\`\n\n`;
            md += `**Recommended Fix:**\n\`\`\`rust\n${vuln.fixedCode}\n\`\`\`\n\n`;
            md += `**Explanation:** ${vuln.explanation}\n\n`;
            if (vuln.computeImpact) {
                md += `**Compute Impact:** ${vuln.computeImpact}\n\n`;
            }
            md += `---\n\n`;
        });
    }

    // Gas Optimizations
    if (result.gasOptimizations && result.gasOptimizations.length > 0) {
        md += `## ⚡ Compute Optimizations\n\n`;
        result.gasOptimizations.forEach((opt, i) => {
            md += `### ${i + 1}. ${opt.title}\n\n`;
            md += `- **Estimated Saving:** ${opt.estimatedSaving}\n`;
            md += `- **Description:** ${opt.description}\n`;
            md += `- **Suggestion:** ${opt.suggestion}\n\n`;
        });
    }

    md += `---\n\n`;
    md += `*Report generated by [AnchorGuard AI](https://anchor-guard-ai.vercel.app) — The AI-Powered Reasoning Auditor for Solana Smart Contracts*\n`;

    return md;
}

export function downloadMarkdown(result: AuditResult) {
    const md = exportToMarkdown(result);
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `anchorguard-audit-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// ========================
// PDF EXPORT
// ========================
export function downloadPDF(result: AuditResult) {
    const { summary } = result;
    const doc = new jsPDF();
    const now = new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' });
    const riskLevel = summary.securityScore < 30 ? 'CRITICAL' : summary.securityScore < 50 ? 'HIGH' : summary.securityScore < 80 ? 'MODERATE' : 'LOW';

    let y = 15;
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;

    const checkPage = (needed: number) => {
        if (y + needed > doc.internal.pageSize.getHeight() - 20) {
            doc.addPage();
            y = 15;
        }
    };

    // Header background
    doc.setFillColor(9, 9, 11); // dark-bg
    doc.rect(0, 0, pageWidth, 45, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('AnchorGuard AI', margin, y + 8);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(153, 69, 255); // solana-purple
    doc.text('Security Audit Report', margin, y + 16);

    doc.setTextColor(160, 160, 180);
    doc.setFontSize(8);
    doc.text(`Generated: ${now}`, margin, y + 24);
    doc.text(`Engine: Hybrid AI (Groq + Gemini)`, margin, y + 30);

    y = 55;

    // Summary Box
    doc.setFillColor(20, 20, 25);
    doc.roundedRect(margin, y, contentWidth, 50, 3, 3, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('AUDIT SUMMARY', margin + 8, y + 12);

    // Score
    const scoreColor = summary.securityScore >= 80 ? [20, 241, 149] : summary.securityScore >= 50 ? [234, 179, 8] : [239, 68, 68];
    doc.setFontSize(36);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(`${summary.securityScore}`, margin + 12, y + 38);

    doc.setFontSize(10);
    doc.setTextColor(120, 120, 140);
    doc.text('/ 100', margin + 38, y + 38);

    // Stats
    const statsX = margin + 80;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    doc.setTextColor(239, 68, 68);
    doc.text(`${summary.critical} Critical`, statsX, y + 18);

    doc.setTextColor(249, 115, 22);
    doc.text(`${summary.high} High`, statsX, y + 28);

    doc.setTextColor(234, 179, 8);
    doc.text(`${summary.medium} Medium`, statsX + 50, y + 18);

    doc.setTextColor(20, 241, 149);
    doc.text(`${summary.safe} Safe`, statsX + 50, y + 28);

    doc.setTextColor(153, 69, 255);
    doc.text(`Risk: ${riskLevel}`, statsX + 100, y + 18);

    doc.setTextColor(120, 120, 140);
    doc.text(`${summary.totalIssues} total issues`, statsX + 100, y + 28);

    y += 60;

    // Vulnerabilities
    if (result.vulnerabilities.length > 0) {
        checkPage(20);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text('Detected Vulnerabilities', margin, y);
        y += 10;

        result.vulnerabilities.forEach((vuln, i) => {
            checkPage(50);

            // Severity color
            const sevColor = vuln.severity === 'critical' ? [239, 68, 68]
                : vuln.severity === 'high' ? [249, 115, 22]
                    : vuln.severity === 'medium' ? [234, 179, 8]
                        : [20, 241, 149];

            // Card background
            doc.setFillColor(20, 20, 25);
            doc.roundedRect(margin, y, contentWidth, 40, 2, 2, 'F');

            // Severity bar
            doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
            doc.rect(margin, y, 3, 40, 'F');

            // Title
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(255, 255, 255);
            doc.text(`${i + 1}. ${vuln.title}`, margin + 8, y + 10);

            // Meta
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(sevColor[0], sevColor[1], sevColor[2]);
            doc.text(`${vuln.severity.toUpperCase()}`, margin + 8, y + 18);

            doc.setTextColor(120, 120, 140);
            doc.text(`Category: ${vuln.category}  |  Line: ~${vuln.line}`, margin + 40, y + 18);

            // Description (wrapped)
            doc.setFontSize(8);
            doc.setTextColor(180, 180, 190);
            const descLines = doc.splitTextToSize(vuln.description, contentWidth - 16);
            doc.text(descLines.slice(0, 2), margin + 8, y + 26);

            y += 46;
        });
    }

    // Gas Optimizations
    if (result.gasOptimizations && result.gasOptimizations.length > 0) {
        checkPage(30);
        y += 5;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text('Compute Optimizations', margin, y);
        y += 10;

        result.gasOptimizations.forEach((opt) => {
            checkPage(30);

            doc.setFillColor(20, 20, 25);
            doc.roundedRect(margin, y, contentWidth, 25, 2, 2, 'F');

            doc.setFillColor(153, 69, 255);
            doc.rect(margin, y, 3, 25, 'F');

            doc.setFontSize(9);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(255, 255, 255);
            doc.text(opt.title, margin + 8, y + 10);

            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(20, 241, 149);
            doc.text(`Saving: ${opt.estimatedSaving}`, margin + 8, y + 18);

            doc.setTextColor(120, 120, 140);
            const suggLines = doc.splitTextToSize(opt.suggestion, contentWidth - 80);
            doc.text(suggLines.slice(0, 1), margin + 60, y + 18);

            y += 30;
        });
    }

    // Footer
    checkPage(20);
    y += 10;
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 120);
    doc.text('Report generated by AnchorGuard AI — The AI-Powered Reasoning Auditor for Solana Smart Contracts', margin, y);
    doc.text('https://anchor-guard-ai.vercel.app', margin, y + 6);

    // Save
    doc.save(`anchorguard-audit-${Date.now()}.pdf`);
}
